"use client";

import { useMemo } from "react";

import { useWebMCPTools } from "../hooks";
import type { UseWebMCPOptions, UseWebMCPResult, WebMCPToolDefinition } from "../types";
import {
  EMPTY_OBJECT_SCHEMA,
  makeTool,
  type CatalogHandler,
  type PreparedCatalogHandler,
} from "./shared";

export type EmptyInput = Record<string, never>;

export interface SearchEquipmentInput {
  readonly query?: string;
  readonly categories?: readonly string[];
  readonly maxWidthCm?: number;
  readonly maxDepthCm?: number;
  readonly accessible?: boolean;
  readonly limit?: number;
}

export interface GetEquipmentInput {
  readonly equipmentId: string;
}

export interface AgentGeneratedRoutineExerciseInput {
  readonly equipmentId: string;
  readonly durationMinutes: number;
  readonly intensity: "easy" | "moderate";
  readonly instructions: readonly string[];
  readonly adaptationReason: string;
}

export interface AgentGeneratedRoutineInput {
  readonly title: string;
  readonly durationMinutes: number;
  readonly exercises: readonly AgentGeneratedRoutineExerciseInput[];
  readonly warmup?: readonly string[];
  readonly cooldown?: readonly string[];
  readonly safetyNotes: readonly string[];
  readonly requiresExpertReview: boolean;
  readonly expertReviewReason?: string;
}

export interface CreatePersonalizedRoutineInput {
  readonly goal: string;
  readonly paymentMode?: "human_checkout" | "agent_wallet";
  readonly routine: AgentGeneratedRoutineInput;
}

export interface GetRoutineProStatusInput {
  readonly orderRef?: string;
}

export interface RecordSessionFeedbackInput {
  readonly sessionId: string;
  readonly perceivedExertion?: number;
  readonly pain?: number;
  readonly notes?: string;
}

export interface GymToolHandlers {
  readonly get_gym_profile: CatalogHandler<EmptyInput>;
  readonly search_equipment: CatalogHandler<SearchEquipmentInput>;
  readonly get_equipment: CatalogHandler<GetEquipmentInput>;
  readonly get_active_context: CatalogHandler<EmptyInput>;
  readonly get_routine_pro_offer: CatalogHandler<EmptyInput>;
  readonly get_routine_pro_status: CatalogHandler<GetRoutineProStatusInput>;
  readonly create_personalized_routine: PreparedCatalogHandler<CreatePersonalizedRoutineInput>;
  readonly record_session_feedback: PreparedCatalogHandler<RecordSessionFeedbackInput>;
}

const routineSchema = {
  type: "object",
  properties: {
    title: {
      type: "string",
      description: "A concise title written by the calling agent for this exact routine.",
      minLength: 2,
      maxLength: 120,
    },
    durationMinutes: {
      type: "integer",
      description: "Total proposed session duration, including warm-up and cooldown.",
      minimum: 10,
      maximum: 120,
    },
    exercises: {
      type: "array",
      description:
        "New exercise blocks generated by the calling agent. Every equipmentId must come from the current Gym tools.",
      minItems: 1,
      maxItems: 12,
      items: {
        type: "object",
        properties: {
          equipmentId: {
            type: "string",
            description: "Verified identifier returned by search_equipment or get_equipment.",
            minLength: 3,
            maxLength: 96,
          },
          durationMinutes: {
            type: "integer",
            minimum: 1,
            maximum: 45,
          },
          intensity: {
            type: "string",
            enum: ["easy", "moderate"],
          },
          instructions: {
            type: "array",
            minItems: 1,
            maxItems: 5,
            items: { type: "string", minLength: 2, maxLength: 180 },
          },
          adaptationReason: {
            type: "string",
            description:
              "Explain how this block responds to the approved request or Passport projection without asserting medical clearance.",
            minLength: 3,
            maxLength: 240,
          },
        },
        required: [
          "equipmentId",
          "durationMinutes",
          "intensity",
          "instructions",
          "adaptationReason",
        ],
        additionalProperties: false,
      },
    },
    warmup: {
      type: "array",
      maxItems: 6,
      items: { type: "string", minLength: 2, maxLength: 180 },
    },
    cooldown: {
      type: "array",
      maxItems: 6,
      items: { type: "string", minLength: 2, maxLength: 180 },
    },
    safetyNotes: {
      type: "array",
      minItems: 1,
      maxItems: 8,
      items: { type: "string", minLength: 2, maxLength: 200 },
    },
    requiresExpertReview: {
      type: "boolean",
      description:
        "Must be true for injury, rehabilitation, post-operative, or undocumented-clearance scenarios.",
    },
    expertReviewReason: {
      type: "string",
      description: "Why physician or qualified physical-therapist review is required.",
      minLength: 3,
      maxLength: 240,
    },
  },
  required: ["title", "durationMinutes", "exercises", "safetyNotes", "requiresExpertReview"],
  additionalProperties: false,
} as const;

export function createGymToolCatalog(handlers: GymToolHandlers): readonly WebMCPToolDefinition[] {
  return [
    makeTool<EmptyInput>(
      {
        name: "get_gym_profile",
        title: "Get Adaptive Gym profile",
        description:
          "Return the gym's facilities, services, access features, and operating constraints.",
        inputSchema: EMPTY_OBJECT_SCHEMA,
        readOnly: true,
      },
      handlers.get_gym_profile,
    ),
    makeTool<SearchEquipmentInput>(
      {
        name: "search_equipment",
        title: "Search gym equipment",
        description:
          "Search equipment actually available at Adaptive Gym using goals, space, and access needs.",
        inputSchema: {
          type: "object",
          properties: {
            query: {
              type: "string",
              description: "Goal, movement, or equipment keyword.",
              maxLength: 120,
            },
            categories: {
              type: "array",
              description: "Optional equipment category filters.",
              items: { type: "string", maxLength: 60 },
              uniqueItems: true,
              maxItems: 8,
            },
            maxWidthCm: {
              type: "number",
              description: "Maximum available operating width in centimeters.",
              minimum: 1,
              maximum: 10_000,
            },
            maxDepthCm: {
              type: "number",
              description: "Maximum available operating depth in centimeters.",
              minimum: 1,
              maximum: 10_000,
            },
            accessible: {
              type: "boolean",
              description: "Require equipment with documented access features.",
            },
            limit: {
              type: "integer",
              description: "Maximum matches to return.",
              minimum: 1,
              maximum: 20,
              default: 2,
            },
          },
          additionalProperties: false,
        },
        readOnly: true,
        untrustedOutput: true,
      },
      handlers.search_equipment,
    ),
    makeTool<GetEquipmentInput>(
      {
        name: "get_equipment",
        title: "Get equipment details",
        description:
          "Return verified specifications and access notes for one gym equipment record.",
        inputSchema: {
          type: "object",
          properties: {
            equipmentId: {
              type: "string",
              description: "Equipment identifier returned by search_equipment.",
              minLength: 1,
              maxLength: 128,
            },
          },
          required: ["equipmentId"],
          additionalProperties: false,
        },
        readOnly: true,
        untrustedOutput: true,
      },
      handlers.get_equipment,
    ),
    makeTool<EmptyInput>(
      {
        name: "get_active_context",
        title: "Get active Gym context",
        description:
          "Return only the currently active, consented Gym projection; never return the full Passport. The result also includes routineBounds (maximum duration, exercise count, per-exercise minutes, and allowed intensities) that any agent-generated routine must satisfy before create_personalized_routine.",
        inputSchema: EMPTY_OBJECT_SCHEMA,
        readOnly: true,
        untrustedOutput: true,
      },
      handlers.get_active_context,
    ),
    makeTool<EmptyInput>(
      {
        name: "get_routine_pro_offer",
        title: "Get Adaptive Routine Pro offer",
        description:
          "Return the exact server-authoritative Adaptive Routine Pro sandbox offer for the active minimum Passport context. Context review, Gym profile, and equipment discovery are free; only validating, paying for, and saving the exact agent-generated routine require Routine Pro.",
        inputSchema: EMPTY_OBJECT_SCHEMA,
        readOnly: true,
      },
      handlers.get_routine_pro_offer,
    ),
    makeTool<GetRoutineProStatusInput>(
      {
        name: "get_routine_pro_status",
        title: "Get Routine Pro payment and save status",
        description:
          "Read the latest relevant Routine Pro order for the active Gym session, including fulfilled orders and safe receipt fields. After any timeout or uncertain payment response, call this tool before taking another action. Never repeat a payment while an order is pending, paid, or fulfilled.",
        inputSchema: {
          type: "object",
          properties: {
            orderRef: {
              type: "string",
              description: "Optional order reference previously returned by Routine Pro.",
              pattern: "^awrp_[a-f0-9]{32}$",
              maxLength: 64,
            },
          },
          additionalProperties: false,
        },
        readOnly: true,
        untrustedOutput: true,
      },
      handlers.get_routine_pro_status,
    ),
    makeTool<CreatePersonalizedRoutineInput>(
      {
        name: "create_personalized_routine",
        title: "Validate, purchase, and save an agent-generated routine",
        description:
          "Submit the exact new structured routine generated by the calling agent. Before calling, the agent must inspect get_active_context, inspect every relevant Gym item through search_equipment/get_equipment, combine only that approved projection and the user's request in its own reasoning context, and show the complete proposal to the user. Never invent equipment, names, models, links, specifications, medical clearance, or professional approval. Preserve uncertainty around injuries and undocumented clearance; set requiresExpertReview=true for injury, rehabilitation, or undocumented-clearance scenarios. Respect routineBounds from get_active_context: durationMinutes within the bound, each equipment item at most once, exercise minutes within the declared duration, easy or moderate intensity only. Obtain the user's exact confirmation of this routine, the $4.99 test USD sandbox payment, the payer, and saving to Passport before submission. If validation fails, the error states the exact reason and no payment is attempted; correct the routine and call again. After a timeout or ambiguous response, call get_routine_pro_status instead of resubmitting. Adaptive Gym validates and hydrates catalog facts; it does not generate the routine.",
        inputSchema: {
          type: "object",
          properties: {
            goal: {
              type: "string",
              description: "The exact goal shown with the proposed routine during confirmation.",
              minLength: 2,
              maxLength: 160,
            },
            paymentMode: {
              type: "string",
              description:
                "Optional sandbox payer. Omit it to use the demo agent wallet when available.",
              enum: ["human_checkout", "agent_wallet"],
            },
            routine: routineSchema,
          },
          required: ["goal", "routine"],
          additionalProperties: false,
        },
        readOnly: false,
        untrustedOutput: true,
      },
      handlers.create_personalized_routine.execute,
      handlers.create_personalized_routine.prepare,
    ),
    makeTool<RecordSessionFeedbackInput>(
      {
        name: "record_session_feedback",
        title: "Record session feedback",
        description:
          "Save post-session effort, pain, and notes after the person confirms the exact feedback.",
        inputSchema: {
          type: "object",
          properties: {
            sessionId: {
              type: "string",
              description: "Opaque public routine reference returned by the active Gym session.",
              minLength: 1,
              maxLength: 128,
            },
            perceivedExertion: {
              type: "integer",
              description: "Perceived effort from 1 to 10.",
              minimum: 1,
              maximum: 10,
            },
            pain: {
              type: "integer",
              description: "Pain reported from 0 to 10.",
              minimum: 0,
              maximum: 10,
            },
            notes: {
              type: "string",
              description: "Optional post-session notes.",
              maxLength: 1_000,
            },
          },
          required: ["sessionId"],
          additionalProperties: false,
        },
        readOnly: false,
        untrustedOutput: true,
      },
      handlers.record_session_feedback.execute,
      handlers.record_session_feedback.prepare,
    ),
  ];
}

export interface UseGymWebMCPOptions extends UseWebMCPOptions {
  readonly handlers: GymToolHandlers;
}

export function useGymWebMCPTools(options: UseGymWebMCPOptions): UseWebMCPResult {
  const { handlers, ...registrationOptions } = options;
  const tools = useMemo(() => createGymToolCatalog(handlers), [handlers]);
  return useWebMCPTools(tools, registrationOptions);
}
