import { EquipmentCatalogSchema } from "@adaptive-world/contracts";

const checkedAt = "2026-08-27";

/** Product specs and media resolve to manufacturers. Only facility ownership is synthetic. */
export const equipmentCatalog = EquipmentCatalogSchema.parse([
  {
    id: "lf_integrity_plus_treadmill",
    slug: "life-fitness-integrity-plus-treadmill",
    name: "Integrity+ Treadmill",
    manufacturer: "Life Fitness",
    model: "Integrity+",
    category: "cardio",
    summary:
      "Commercial treadmill with a 20.3 cm step-up height, 15% incline and Flex Deck shock absorption.",
    dimensionsCm: { length: 209, width: 92, height: 142 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Walking", "Incline walking", "Running", "Speed-controlled warm-up"],
    accessibility: ["20.3 cm step-up height", "Front and side handrails", "Quick controls"],
    suitabilityTags: ["walking", "running", "warm-up", "cardio"],
    locationZone: "Cardio floor · C01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.lifefitness.com/en-us/catalog/cardio/treadmills/integrity-plus",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/Equipment/Cardio/Integrity%20Plus/Integrity-Treadmill-with-SE4-console-24-inch-in-Black-Onyx.png?h=630&w=1200",
    imageAlt: "Life Fitness Integrity+ commercial treadmill in Black Onyx",
  },
  {
    id: "lf_integrity_plus_elliptical",
    slug: "life-fitness-integrity-plus-elliptical",
    name: "Integrity+ Elliptical Cross-Trainer",
    manufacturer: "Life Fitness",
    model: "Integrity+",
    category: "cardio",
    summary:
      "Commercial elliptical with a 51 cm stride, multi-grip moving handles and oversized pedals.",
    dimensionsCm: { length: 218, width: 73, height: 163 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Low-impact cardio", "Forward stride", "Upper and lower body conditioning"],
    accessibility: ["24 cm step-up height", "Stationary handles", "Oversized pedals"],
    suitabilityTags: ["low-impact", "cardio", "cross-training"],
    locationZone: "Cardio floor · C02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/ellipticals/integrity-cardio-elliptical-cross-trainer",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/Equipment/Cardio/Integrity%20Plus/Crosstrainer/INTEGRITY-PLUS_Crosstrainer_SE4-24inch_Black-Onyx_3000-x-3000.png?h=630&w=1200",
    imageAlt: "Life Fitness Integrity+ Elliptical Cross-Trainer",
  },
  {
    id: "lf_heat_row",
    slug: "life-fitness-heat-row",
    name: "Heat Row",
    manufacturer: "Life Fitness",
    model: "Heat Row",
    category: "cardio",
    summary:
      "Commercial rowing ergometer with transport wheels, aluminium rail and a 45 cm seat height.",
    dimensionsCm: { length: 216, width: 71, height: 120 },
    requiredClearanceCm: 46,
    maxUserWeightKg: 150,
    power: "self-powered",
    stations: 1,
    capabilities: ["Rowing", "Full-body conditioning", "Cadence-controlled warm-up"],
    accessibility: ["45 cm seat height", "Transport handle", "Foot straps"],
    suitabilityTags: ["rowing", "warm-up", "full-body", "cardio"],
    locationZone: "Cardio floor · C03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.lifefitness.com/en-us/catalog/cardio/rowers/heat-row",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/MediaSync/149-966-life-fitness-heat-row-three-quarter.png?h=630&w=1200",
    imageAlt: "Life Fitness Heat Row rowing ergometer",
  },
  {
    id: "lf_integrity_recumbent",
    slug: "life-fitness-integrity-plus-recumbent-bike",
    name: "Integrity+ Lifecycle Recumbent Bike",
    manufacturer: "Life Fitness",
    model: "Integrity+ Lifecycle",
    category: "cardio",
    summary:
      "Commercial recumbent cycle with step-through design, lumbar-support seat and wide pedals.",
    dimensionsCm: { length: 179, width: 66, height: 131 },
    requiredClearanceCm: 46,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Seated cycling", "Low-impact cardio", "Cadence-controlled warm-up"],
    accessibility: ["Step-through design", "Wrap-around seat lever", "Lumbar-support seat"],
    suitabilityTags: ["seated", "low-impact", "cycling", "cardio"],
    locationZone: "Cardio floor · C04",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/bikes-indoor-cycles/integrity-lifecycle-recumbent-bike",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/MediaSync/256-562-life-fitness-integrity-series-recumbent-bike-with-24-inch-se4-in-black-onyx.png?h=630&w=1200",
    imageAlt: "Life Fitness Integrity+ Lifecycle Recumbent Bike",
  },
  {
    id: "scifit_pro2_total_body",
    slug: "scifit-pro2-total-body",
    name: "PRO2 Total Body",
    manufacturer: "SCIFIT",
    model: "PRO2",
    category: "rehabilitation",
    summary:
      "Upper-body exerciser and recumbent cycle with dependent motion and a removable-seat option.",
    dimensionsCm: { length: 155, width: 76, height: 157 },
    requiredClearanceCm: 91,
    maxUserWeightKg: 226,
    power: "self-powered",
    stations: 1,
    capabilities: ["Upper-body ergometry", "Recumbent cycling", "Bi-directional exercise"],
    accessibility: ["True step-through", "Removable seat", "Wheelchair-accessible setup"],
    suitabilityTags: ["inclusive", "seated", "upper-body", "rehabilitation"],
    locationZone: "Adaptive training · A01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/bikes-indoor-cycles/pro2-total-body",
    sourceLabel: "SCIFIT / Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/Equipment/Cardio/SciFit/Pro2-TotalBody/SciFit-PRO2-Total-Body-1.jpg?h=630&w=1200",
    imageAlt: "SCIFIT PRO2 Total Body inclusive exercise station",
  },
  {
    id: "lf_insignia_chest_press",
    slug: "life-fitness-insignia-chest-press",
    name: "Insignia Series Chest Press",
    manufacturer: "Life Fitness",
    model: "SS-CP",
    category: "selectorized-strength",
    summary:
      "Selectorized chest press with independent converging arms and an adjustable seat position.",
    dimensionsCm: { length: 110, width: 140, height: 148 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Horizontal pressing", "Independent-arm strength", "Supported upper body"],
    accessibility: ["Open entry", "Seat-height adjustment", "Instruction placard"],
    suitabilityTags: ["strength", "push", "supported", "upper-body"],
    locationZone: "Guided strength · S01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-chest-press",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/Equipment/Strength/Selectorised/Insignia%20Series/Insignia%20Chest%20Press/LF-INSIGNIA-Chest-Press-Black-Thumbnail.png?h=630&w=1200",
    imageAlt: "Life Fitness Insignia Series Chest Press",
  },
  {
    id: "lf_insignia_row",
    slug: "life-fitness-insignia-row",
    name: "Insignia Series Row",
    manufacturer: "Life Fitness",
    model: "SS-RW",
    category: "selectorized-strength",
    summary: "Selectorized row with a supported seated position and independent pulling arms.",
    dimensionsCm: { length: 124, width: 141, height: 148 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Horizontal pulling", "Independent-arm strength", "Supported upper body"],
    accessibility: ["Open entry", "Seat-height adjustment", "Instruction placard"],
    suitabilityTags: ["strength", "pull", "supported", "upper-body"],
    locationZone: "Guided strength · S02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-row",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/MediaSync/405-232-row.png?h=630&w=1200",
    imageAlt: "Life Fitness Insignia Series Row",
  },
  {
    id: "lf_insignia_pec_rear_delt",
    slug: "life-fitness-insignia-pectoral-fly-rear-deltoid",
    name: "Insignia Pectoral Fly / Rear Deltoid",
    manufacturer: "Life Fitness",
    model: "SS-FLY",
    category: "selectorized-strength",
    summary:
      "Dual-purpose selectorized station for pectoral fly and supported rear-deltoid movement.",
    dimensionsCm: { length: 203, width: 197, height: 203 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Pectoral fly", "Rear-deltoid movement", "Supported upper body"],
    accessibility: ["Adjustable seat", "Two movement configurations", "Instruction placard"],
    suitabilityTags: ["strength", "upper-body", "supported", "dual-purpose"],
    locationZone: "Guided strength · S03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-pectoral-fly-rear-deltoid",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/Equipment/Strength/Selectorised/Insignia%20Series/Insignia%20Pectoral%20Fly%20Read%20Deltoid/LF-INSIGNIA-Pectoral-Fly-Rear-Deltoid-Black-Thumbnail.png?h=630&w=1200",
    imageAlt: "Life Fitness Insignia Pectoral Fly and Rear Deltoid station",
  },
  {
    id: "lf_insignia_back_extension",
    slug: "life-fitness-insignia-back-extension",
    name: "Insignia Series Back Extension",
    manufacturer: "Life Fitness",
    model: "SS-BE",
    category: "selectorized-strength",
    summary: "Supported back-extension station with a five-position start mechanism.",
    dimensionsCm: { length: 139, width: 106, height: 148 },
    requiredClearanceCm: 61,
    power: "none",
    stations: 1,
    capabilities: ["Controlled trunk extension", "Supported posterior-chain movement"],
    accessibility: ["Five start positions", "Supported seat", "Instruction placard"],
    suitabilityTags: ["strength", "posterior-chain", "supported"],
    locationZone: "Guided strength · S04",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-back-extension",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/MediaSync/42-118-insignia-series-back-extension-1-.jpg?h=630&w=1200",
    imageAlt: "Life Fitness Insignia Series Back Extension",
  },
  {
    id: "lf_dual_adjustable_pulley",
    slug: "life-fitness-dual-adjustable-pulley",
    name: "Dual Adjustable Pulley",
    manufacturer: "Life Fitness",
    model: "CMDAP",
    category: "functional-training",
    summary:
      "Commercial dual cable station with independently adjustable carriages and weight stacks.",
    dimensionsCm: { length: 112, width: 158, height: 242 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 2,
    capabilities: ["Cable push", "Cable pull", "Multi-planar strength", "Two-user setup"],
    accessibility: ["Low starting resistance", "Independent carriage heights", "Open approach"],
    suitabilityTags: ["cables", "functional", "strength", "multi-planar"],
    locationZone: "Functional floor · F01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/cable-machines-functional-trainers/life-fitness-dual-adjustable-pulley",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://www.lifefitness.com/Kentico13CoreBase/media/LFMedia/LifeFitnessImages/MediaSync/315-975-signature-series-dap.png?h=630&w=1200",
    imageAlt: "Life Fitness Dual Adjustable Pulley cable station",
  },
  {
    id: "rogue_manta_ray_bench",
    slug: "rogue-manta-ray-adjustable-bench",
    name: "Manta Ray Adjustable Bench",
    manufacturer: "Rogue Fitness",
    model: "Manta Ray",
    category: "free-weights",
    summary:
      "Commercial adjustable bench with a 17.5 inch flat height and 57 by 24.75 inch footprint.",
    dimensionsCm: { length: 145, width: 63, height: 45 },
    requiredClearanceCm: 91,
    power: "none",
    stations: 1,
    capabilities: ["Flat bench support", "Incline bench support", "Decline bench support"],
    accessibility: ["Wheeled repositioning", "Stable 17.5 inch flat height"],
    suitabilityTags: ["bench", "free-weights", "supported", "adjustable"],
    locationZone: "Free weights · W01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.roguefitness.com/rogue-manta-ray-adjustable-bench",
    sourceLabel: "Rogue Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl:
      "https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_1600,b_rgb:ffffff/catalog/Strength%20Equipment/Strength%20Training/Weight%20Benches/Adjustable%20:%20Incline%20Benches/RF0983-BLACK-MG/2024%20MG%20colors/RF0983-BLACK-MG-Red-H_yetdt4.png",
    imageAlt: "Rogue Fitness Manta Ray Adjustable Bench",
  },
  {
    id: "eleiko_prestera_half_rack",
    slug: "eleiko-prestera-half-rack-black",
    name: "Prestera Half Rack Black",
    manufacturer: "Eleiko",
    model: "BD-1-357",
    category: "free-weights",
    summary:
      "Commercial half rack with J-cups, magnetic safety arms, pull-up bar and plate storage.",
    dimensionsCm: { length: 130, width: 196, height: 235 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 1,
    capabilities: ["Barbell squat", "Bench press setup", "Pull-up", "Barbell safety arms"],
    accessibility: ["Numbered adjustments", "Roller J-cups", "Adjustable safety arms"],
    suitabilityTags: ["barbell", "strength", "rack", "advanced"],
    locationZone: "Free weights · W02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://eleiko.com/en-us/equipment/racksandrigs/racks/3085609-03-eleiko-prestera-half-rack-black",
    sourceLabel: "Eleiko product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "https://media.eleiko.com/images/upload/4x5/3085609-03_10.jpg",
    imageAlt: "Eleiko Prestera Half Rack in black",
  },
]);

export const equipmentCatalogVersion = "verified-2026-08-27";
