import { EquipmentCatalogSchema } from "@adaptive-world/contracts";

const checkedAt = "2026-08-29";

/** Product specs resolve to cited manufacturers; AI-generated imagery is illustrative and facility ownership is synthetic. */
export const equipmentCatalog = EquipmentCatalogSchema.parse([
  {
    id: "lf_integrity_plus_treadmill",
    slug: "life-fitness-integrity-plus-treadmill",
    name: "Integrity+ Treadmill",
    manufacturer: "Life Fitness",
    model: "Integrity+",
    category: "cardio",
    summary:
      "Commercial treadmill with a 20.3 cm step-up height, 15% incline and Flex Deck shock absorption.",
    dimensionsCm: { length: 209, width: 92, height: 142 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Walking", "Incline walking", "Running", "Speed-controlled warm-up"],
    accessibility: ["20.3 cm step-up height", "Front and side handrails", "Quick controls"],
    suitabilityTags: ["walking", "running", "warm-up", "cardio"],
    locationZone: "Cardio floor · C01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.lifefitness.com/en-us/catalog/cardio/treadmills/integrity-plus",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-integrity-plus-treadmill.webp",
    imageAlt: "AI-generated studio visualization of a Life Fitness Integrity+ commercial treadmill",
  },
  {
    id: "lf_integrity_plus_elliptical",
    slug: "life-fitness-integrity-plus-elliptical",
    name: "Integrity+ Elliptical Cross-Trainer",
    manufacturer: "Life Fitness",
    model: "Integrity+",
    category: "cardio",
    summary:
      "Commercial elliptical with a 51 cm stride, multi-grip moving handles and oversized pedals.",
    dimensionsCm: { length: 218, width: 73, height: 163 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Low-impact cardio", "Forward stride", "Upper and lower body conditioning"],
    accessibility: ["24 cm step-up height", "Stationary handles", "Oversized pedals"],
    suitabilityTags: ["low-impact", "cardio", "cross-training"],
    locationZone: "Cardio floor · C02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/ellipticals/integrity-cardio-elliptical-cross-trainer",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-integrity-plus-elliptical.webp",
    imageAlt:
      "AI-generated studio visualization of a Life Fitness Integrity+ elliptical cross-trainer",
  },
  {
    id: "lf_heat_row",
    slug: "life-fitness-heat-row",
    name: "Heat Row",
    manufacturer: "Life Fitness",
    model: "Heat Row",
    category: "cardio",
    summary:
      "Commercial rowing ergometer with transport wheels, aluminium rail and a 45 cm seat height.",
    dimensionsCm: { length: 216, width: 71, height: 120 },
    requiredClearanceCm: 46,
    maxUserWeightKg: 150,
    power: "self-powered",
    stations: 1,
    capabilities: ["Rowing", "Full-body conditioning", "Cadence-controlled warm-up"],
    accessibility: ["45 cm seat height", "Transport handle", "Foot straps"],
    suitabilityTags: ["rowing", "warm-up", "full-body", "cardio"],
    locationZone: "Cardio floor · C03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.lifefitness.com/en-us/catalog/cardio/rowers/heat-row",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-heat-row.webp",
    imageAlt: "AI-generated studio visualization of a Life Fitness Heat Row rowing ergometer",
  },
  {
    id: "lf_integrity_recumbent",
    slug: "life-fitness-integrity-plus-recumbent-bike",
    name: "Integrity+ Lifecycle Recumbent Bike",
    manufacturer: "Life Fitness",
    model: "Integrity+ Lifecycle",
    category: "cardio",
    summary:
      "Commercial recumbent cycle with step-through design, lumbar-support seat and wide pedals.",
    dimensionsCm: { length: 179, width: 66, height: 131 },
    requiredClearanceCm: 46,
    maxUserWeightKg: 181,
    power: "120v",
    stations: 1,
    capabilities: ["Seated cycling", "Low-impact cardio", "Cadence-controlled warm-up"],
    accessibility: ["Step-through design", "Wrap-around seat lever", "Lumbar-support seat"],
    suitabilityTags: ["seated", "low-impact", "cycling", "cardio"],
    locationZone: "Cardio floor · C04",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/bikes-indoor-cycles/integrity-lifecycle-recumbent-bike",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-integrity-plus-recumbent-bike.webp",
    imageAlt:
      "AI-generated studio visualization of a Life Fitness Integrity+ step-through recumbent bike",
  },
  {
    id: "scifit_pro2_total_body",
    slug: "scifit-pro2-total-body",
    name: "PRO2 Total Body",
    manufacturer: "SCIFIT",
    model: "PRO2",
    category: "rehabilitation",
    summary:
      "Upper-body exerciser and recumbent cycle with dependent motion and a removable-seat option.",
    dimensionsCm: { length: 155, width: 76, height: 157 },
    requiredClearanceCm: 91,
    maxUserWeightKg: 226,
    power: "self-powered",
    stations: 1,
    capabilities: ["Upper-body ergometry", "Recumbent cycling", "Bi-directional exercise"],
    accessibility: ["True step-through", "Removable seat", "Wheelchair-accessible setup"],
    suitabilityTags: ["inclusive", "seated", "upper-body", "rehabilitation"],
    locationZone: "Adaptive training · A01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/cardio/bikes-indoor-cycles/pro2-total-body",
    sourceLabel: "SCIFIT / Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/scifit-pro2-total-body.webp",
    imageAlt: "AI-generated studio visualization of a SCIFIT PRO2 inclusive total-body ergometer",
  },
  {
    id: "lf_insignia_chest_press",
    slug: "life-fitness-insignia-chest-press",
    name: "Insignia Series Chest Press",
    manufacturer: "Life Fitness",
    model: "SS-CP",
    category: "selectorized-strength",
    summary:
      "Selectorized chest press with independent converging arms and an adjustable seat position.",
    dimensionsCm: { length: 110, width: 140, height: 148 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Horizontal pressing", "Independent-arm strength", "Supported upper body"],
    accessibility: ["Open entry", "Seat-height adjustment", "Instruction placard"],
    suitabilityTags: ["strength", "push", "supported", "upper-body"],
    locationZone: "Guided strength · S01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-chest-press",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-insignia-chest-press.webp",
    imageAlt: "AI-generated studio visualization of a Life Fitness Insignia supported chest press",
  },
  {
    id: "lf_insignia_row",
    slug: "life-fitness-insignia-row",
    name: "Insignia Series Row",
    manufacturer: "Life Fitness",
    model: "SS-RW",
    category: "selectorized-strength",
    summary: "Selectorized row with a supported seated position and independent pulling arms.",
    dimensionsCm: { length: 124, width: 141, height: 148 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Horizontal pulling", "Independent-arm strength", "Supported upper body"],
    accessibility: ["Open entry", "Seat-height adjustment", "Instruction placard"],
    suitabilityTags: ["strength", "pull", "supported", "upper-body"],
    locationZone: "Guided strength · S02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-row",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-insignia-row.webp",
    imageAlt: "AI-generated studio visualization of a Life Fitness Insignia supported seated row",
  },
  {
    id: "lf_insignia_pec_rear_delt",
    slug: "life-fitness-insignia-pectoral-fly-rear-deltoid",
    name: "Insignia Pectoral Fly / Rear Deltoid",
    manufacturer: "Life Fitness",
    model: "SS-FLY",
    category: "selectorized-strength",
    summary:
      "Dual-purpose selectorized station for pectoral fly and supported rear-deltoid movement.",
    dimensionsCm: { length: 203, width: 197, height: 203 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 136,
    power: "none",
    stations: 1,
    capabilities: ["Pectoral fly", "Rear-deltoid movement", "Supported upper body"],
    accessibility: ["Adjustable seat", "Two movement configurations", "Instruction placard"],
    suitabilityTags: ["strength", "upper-body", "supported", "dual-purpose"],
    locationZone: "Guided strength · S03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-pectoral-fly-rear-deltoid",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-insignia-pectoral-fly-rear-deltoid.webp",
    imageAlt:
      "AI-generated studio visualization of a Life Fitness Insignia pectoral fly and rear-deltoid station",
  },
  {
    id: "lf_insignia_back_extension",
    slug: "life-fitness-insignia-back-extension",
    name: "Insignia Series Back Extension",
    manufacturer: "Life Fitness",
    model: "SS-BE",
    category: "selectorized-strength",
    summary: "Supported back-extension station with a five-position start mechanism.",
    dimensionsCm: { length: 139, width: 106, height: 148 },
    requiredClearanceCm: 61,
    power: "none",
    stations: 1,
    capabilities: ["Controlled trunk extension", "Supported posterior-chain movement"],
    accessibility: ["Five start positions", "Supported seat", "Instruction placard"],
    suitabilityTags: ["strength", "posterior-chain", "supported"],
    locationZone: "Guided strength · S04",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/selectorized/insignia-series-back-extension",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-insignia-back-extension.webp",
    imageAlt:
      "AI-generated studio visualization of a Life Fitness Insignia supported back-extension station",
  },
  {
    id: "lf_dual_adjustable_pulley",
    slug: "life-fitness-dual-adjustable-pulley",
    name: "Dual Adjustable Pulley",
    manufacturer: "Life Fitness",
    model: "CMDAP",
    category: "functional-training",
    summary:
      "Commercial dual-cable functional trainer with independently adjustable carriages and weight stacks.",
    dimensionsCm: { length: 112, width: 158, height: 242 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 2,
    capabilities: ["Cable push", "Cable pull", "Multi-planar strength", "Two-user setup"],
    accessibility: ["Low starting resistance", "Independent carriage heights", "Open approach"],
    suitabilityTags: ["cables", "functional", "strength", "multi-planar"],
    locationZone: "Functional floor · F01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/cable-machines-functional-trainers/life-fitness-dual-adjustable-pulley",
    sourceLabel: "Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/life-fitness-dual-adjustable-pulley.webp",
    imageAlt: "AI-generated studio visualization of a Life Fitness dual adjustable pulley station",
  },
  {
    id: "rogue_manta_ray_bench",
    slug: "rogue-manta-ray-adjustable-bench",
    name: "Manta Ray Adjustable Bench",
    manufacturer: "Rogue Fitness",
    model: "Manta Ray",
    category: "free-weights",
    summary:
      "Commercial adjustable bench with a 17.5 inch flat height and 57 by 24.75 inch footprint.",
    dimensionsCm: { length: 145, width: 63, height: 45 },
    requiredClearanceCm: 91,
    power: "none",
    stations: 1,
    capabilities: ["Flat bench support", "Incline bench support", "Decline bench support"],
    accessibility: ["Wheeled repositioning", "Stable 17.5 inch flat height"],
    suitabilityTags: ["bench", "free-weights", "supported", "adjustable"],
    locationZone: "Free weights · W01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.roguefitness.com/rogue-manta-ray-adjustable-bench",
    sourceLabel: "Rogue Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/rogue-manta-ray-adjustable-bench.webp",
    imageAlt: "AI-generated studio visualization of a Rogue Manta Ray adjustable training bench",
  },
  {
    id: "eleiko_prestera_half_rack",
    slug: "eleiko-prestera-half-rack-black",
    name: "Prestera Half Rack Black",
    manufacturer: "Eleiko",
    model: "BD-1-357",
    category: "free-weights",
    summary:
      "Commercial half rack with J-cups, magnetic safety arms, pull-up bar and plate storage.",
    dimensionsCm: { length: 130, width: 196, height: 235 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 1,
    capabilities: ["Barbell squat", "Bench press setup", "Pull-up", "Barbell safety arms"],
    accessibility: ["Numbered adjustments", "Roller J-cups", "Adjustable safety arms"],
    suitabilityTags: ["barbell", "strength", "rack", "advanced"],
    locationZone: "Free weights · W02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://eleiko.com/en-us/equipment/racksandrigs/racks/3085609-03-eleiko-prestera-half-rack-black",
    sourceLabel: "Eleiko product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/eleiko-prestera-half-rack-black.webp",
    imageAlt: "AI-generated studio visualization of an Eleiko Prestera barbell half rack",
  },
  {
    id: "hs_linear_leg_press",
    slug: "hammer-strength-linear-leg-press",
    name: "Plate Loaded Linear Leg Press",
    manufacturer: "Hammer Strength",
    model: "HSLLP",
    category: "plate-loaded-strength",
    summary:
      "45-degree plate-loaded leg press with an adjustable back pad, large foot platform and range-of-motion control.",
    dimensionsCm: { length: 241, width: 165, height: 145 },
    operatingDimensionsCm: { length: 485, width: 409, height: 145 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 1,
    capabilities: [
      "45-degree leg press",
      "Bilateral lower-body strength",
      "Range-limited pressing",
    ],
    accessibility: [
      "Adjustable back pad",
      "Large non-slip foot platform",
      "Range-of-motion adjustment",
    ],
    suitabilityTags: ["strength", "lower-body", "plate-loaded", "supported"],
    locationZone: "Plate strength · P01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/plate-loaded/plate-loaded-linear-leg-press",
    sourceLabel: "Hammer Strength / Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/hammer-strength-linear-leg-press.webp",
    imageAlt:
      "AI-generated studio visualization of a Hammer Strength plate-loaded linear leg press",
  },
  {
    id: "hs_iso_lateral_high_row",
    slug: "hammer-strength-iso-lateral-high-row",
    name: "Plate Loaded Iso-Lateral High Row",
    manufacturer: "Hammer Strength",
    model: "IL-HR",
    category: "plate-loaded-strength",
    summary:
      "Plate-loaded high row with independent converging arms plus adjustable seat and thigh-pad positions.",
    dimensionsCm: { length: 163, width: 145, height: 201 },
    operatingDimensionsCm: { length: 407, width: 389, height: 201 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 1,
    capabilities: [
      "High-angle pulling",
      "Independent-arm strength",
      "Supported upper-body training",
    ],
    accessibility: ["Adjustable seat", "Adjustable thigh pad", "Independent movement arms"],
    suitabilityTags: ["strength", "pull", "plate-loaded", "upper-body"],
    locationZone: "Plate strength · P02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.lifefitness.com/en-us/catalog/strength-training/plate-loaded/plate-loaded-iso-lateral-high-row",
    sourceLabel: "Hammer Strength / Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/hammer-strength-iso-lateral-high-row.webp",
    imageAlt:
      "AI-generated studio visualization of a Hammer Strength plate-loaded iso-lateral high row",
  },
  {
    id: "rogue_sml_2c_squat_stand",
    slug: "rogue-sml-2c-squat-stand",
    name: "SML-2C Squat Stand",
    manufacturer: "Rogue Fitness",
    model: "SML-2C",
    category: "free-weights",
    summary:
      "Commercial squat stand with 3-by-3-inch uprights, J-cups and an integrated single pull-up bar.",
    dimensionsCm: { length: 122, width: 124, height: 234 },
    operatingDimensionsCm: { length: 366, width: 368, height: 234 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 1,
    capabilities: ["Barbell squat", "Bench-press setup", "Pull-up"],
    accessibility: ["Westside hole spacing", "Adjustable J-cups", "Open walk-in footprint"],
    suitabilityTags: ["barbell", "strength", "squat", "free-weights"],
    locationZone: "Free weights · W03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.roguefitness.com/rogue-sml-2c-squat-stand",
    sourceLabel: "Rogue Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/rogue-sml-2c-squat-stand.webp",
    imageAlt: "AI-generated studio visualization of a Rogue SML-2C commercial squat stand",
  },
  {
    id: "torque_hex_dumbbell_rack",
    slug: "torque-rubber-hex-dumbbell-set-storage-rack",
    name: "5–50 lb Rubber Hex Dumbbell Set + Rack",
    manufacturer: "Torque Fitness",
    model: "XG-DBRH550-USR4",
    category: "free-weights",
    summary:
      "Ten matched dumbbell pairs from 5 to 50 pounds in five-pound increments on a three-tier storage rack.",
    dimensionsCm: { length: 119, width: 52, height: 102 },
    operatingDimensionsCm: { length: 301, width: 234, height: 102 },
    requiredClearanceCm: 91,
    power: "none",
    stations: 1,
    capabilities: ["Dumbbell strength", "Loaded carries", "Unilateral training"],
    accessibility: [
      "Three open storage tiers",
      "Ten graduated weight pairs",
      "Raised dumbbell storage",
    ],
    suitabilityTags: ["dumbbells", "strength", "free-weights", "unilateral"],
    locationZone: "Free weights · W04",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.torquefitness.com/products/5-50-rubber-hex-db-set-w-4-storage-rack",
    sourceLabel: "Torque Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/torque-rubber-hex-dumbbell-set-storage-rack.webp",
    imageAlt:
      "AI-generated studio visualization of a Torque three-tier rack with ten dumbbell pairs",
  },
  {
    id: "torque_f9_functional_trainer",
    slug: "torque-free-standing-f9-functional-trainer",
    name: "Free-Standing F9 Fold-Away Functional Trainer",
    manufacturer: "Torque Fitness",
    model: "F9-150",
    category: "functional-training",
    summary:
      "Twin-stack functional trainer with two adjustable cable arms and a cabinet that folds closed for storage.",
    dimensionsCm: { length: 155, width: 177, height: 213 },
    operatingDimensionsCm: { length: 274, width: 244, height: 213 },
    requiredClearanceCm: 122,
    power: "none",
    stations: 2,
    capabilities: ["Cable push", "Cable pull", "Multi-planar strength", "Two-arm training"],
    accessibility: ["Adjustable cable-arm heights", "Fold-away doors", "Open standing approach"],
    suitabilityTags: ["cables", "functional", "strength", "multi-planar"],
    locationZone: "Functional floor · F02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://www.torquefitness.com/products/free-standing-f9-fold-away-functional-trainer",
    sourceLabel: "Torque Fitness product page and linked assembly guide",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/torque-free-standing-f9-functional-trainer.webp",
    imageAlt: "AI-generated studio visualization of a Torque F9 fold-away functional trainer",
  },
  {
    id: "torque_tank_m1",
    slug: "torque-tank-m1-push-sled",
    name: "TANK M1 Push Sled",
    manufacturer: "Torque Fitness",
    model: "TANK M1",
    category: "functional-training",
    summary:
      "All-surface push sled with magnetic resistance, dual push positions and solid airless tires.",
    dimensionsCm: { length: 115, width: 81, height: 95 },
    operatingDimensionsCm: { length: 298, width: 81, height: 95 },
    requiredClearanceCm: 183,
    power: "none",
    stations: 1,
    capabilities: ["Sled push", "Sled pull", "Resisted walking", "Conditioning intervals"],
    accessibility: [
      "Dual push-handle positions",
      "Magnetic resistance",
      "No added plates required",
    ],
    suitabilityTags: ["sled", "functional", "conditioning", "resistance"],
    locationZone: "Functional floor · F03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.torquefitness.com/products/tank-m1-push-sled",
    sourceLabel: "Torque Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/torque-tank-m1-push-sled.webp",
    imageAlt: "AI-generated studio visualization of a Torque TANK M1 magnetic-resistance sled",
  },
  {
    id: "balanced_body_allegro_2",
    slug: "balanced-body-allegro-2-reformer",
    name: "Allegro 2 Reformer",
    manufacturer: "Balanced Body",
    model: "Allegro 2",
    category: "pilates-mobility",
    summary:
      "Commercial Pilates reformer with a moving footbar, built-in standing platform and five springs.",
    dimensionsCm: { length: 239, width: 79, height: 38 },
    operatingDimensionsCm: { length: 421, width: 261, height: 38 },
    requiredClearanceCm: 91,
    power: "none",
    stations: 1,
    capabilities: ["Reformer Pilates", "Spring-resisted mobility", "Supported lower-body movement"],
    accessibility: ["Moving footbar", "Built-in standing platform", "Optional 15-inch studio legs"],
    suitabilityTags: ["pilates", "mobility", "low-impact", "spring-resistance"],
    locationZone: "Pilates studio · M01",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.pilates.com/products/allegro-2-pilates-reformer/",
    sourceLabel: "Balanced Body product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/balanced-body-allegro-2-reformer.webp",
    imageAlt: "AI-generated studio visualization of a Balanced Body Allegro 2 Pilates reformer",
  },
  {
    id: "balanced_body_combo_chair",
    slug: "balanced-body-combo-chair",
    name: "Combo Chair",
    manufacturer: "Balanced Body",
    model: "Combo Chair",
    category: "pilates-mobility",
    summary:
      "Compact Pilates chair with a split-or-single pedal, four springs and removable support handles.",
    dimensionsCm: { length: 72, width: 70, height: 65 },
    operatingDimensionsCm: { length: 254, width: 252, height: 65 },
    requiredClearanceCm: 91,
    power: "none",
    stations: 1,
    capabilities: ["Chair Pilates", "Spring-resisted strength", "Standing balance support"],
    accessibility: ["Four-height support handles", "Split or single pedal", "Transport wheels"],
    suitabilityTags: ["pilates", "mobility", "balance", "spring-resistance"],
    locationZone: "Pilates studio · M02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.pilates.com/products/combo-pilates-chair/",
    sourceLabel: "Balanced Body product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/balanced-body-combo-chair.webp",
    imageAlt: "AI-generated studio visualization of a Balanced Body split-pedal Combo Chair",
  },
  {
    id: "nustep_t6max",
    slug: "nustep-t6max-recumbent-cross-trainer",
    name: "T6MAX Recumbent Cross Trainer",
    manufacturer: "NuStep",
    model: "T6MAX",
    category: "rehabilitation",
    summary:
      "Inclusive recumbent cross trainer with a wide 360-degree swivel seat, StrideLock and adjustable arms.",
    dimensionsCm: { length: 185, width: 76, height: 117 },
    operatingDimensionsCm: { length: 307, width: 198, height: 117 },
    requiredClearanceCm: 61,
    maxUserWeightKg: 272,
    power: "ac-adapter",
    stations: 1,
    capabilities: ["Recumbent stepping", "Upper and lower body conditioning", "Low-impact cardio"],
    accessibility: ["360-degree swivel seat", "Low step-through", "StrideLock transfer support"],
    suitabilityTags: ["inclusive", "seated", "low-impact", "rehabilitation"],
    locationZone: "Adaptive training · A02",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl: "https://www.nustep.com/product/t6max/",
    sourceLabel: "NuStep product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/nustep-t6max-recumbent-cross-trainer.webp",
    imageAlt: "AI-generated studio visualization of a NuStep T6MAX recumbent cross trainer",
  },
  {
    id: "scifit_stepone",
    slug: "scifit-stepone-recumbent-stepper",
    name: "StepOne Recumbent Stepper",
    manufacturer: "SCIFIT",
    model: "StepOne",
    category: "rehabilitation",
    summary:
      "Low-step recumbent stepper with a removable swiveling seat and direct wheelchair access.",
    dimensionsCm: { length: 173, width: 76, height: 122 },
    operatingDimensionsCm: { length: 355, width: 258, height: 122 },
    requiredClearanceCm: 91,
    maxUserWeightKg: 204,
    power: "self-powered",
    stations: 1,
    capabilities: [
      "Recumbent stepping",
      "Dependent upper and lower body motion",
      "Low-impact cardio",
    ],
    accessibility: ["Two-inch step-through", "Removable swivel seat", "Direct wheelchair access"],
    suitabilityTags: ["inclusive", "seated", "low-impact", "rehabilitation"],
    locationZone: "Adaptive training · A03",
    available: true,
    verifiedProduct: true,
    syntheticFacilityInventory: true,
    sourceUrl:
      "https://shop.lifefitness.com/products/stepone-recumbent-stepper-prem-seat-cool-gray",
    sourceLabel: "SCIFIT / Life Fitness product specifications",
    sourceCheckedAt: checkedAt,
    imageUrl: "/images/equipment/scifit-stepone-recumbent-stepper.webp",
    imageAlt: "AI-generated studio visualization of a SCIFIT StepOne recumbent stepper",
  },
]);

export const equipmentCatalogVersion = "verified-2026-08-29";
