import {
  EquipmentCatalogSchema,
  type Equipment,
  type EquipmentCategory,
} from "@adaptive-world/contracts";

type EquipmentSeed = readonly [
  name: string,
  manufacturer: string,
  model: string,
  category: EquipmentCategory,
  capability: string,
  suitability: string,
];

const equipmentSeeds = [
  [
    "Performance Treadmill",
    "Life Fitness",
    "Integrity+",
    "cardio",
    "Incline walking and running",
    "running",
  ],
  ["Low-Step Treadmill", "SportsArt", "T655MS", "cardio", "Low step-up walking", "easy-entry"],
  ["Curved Manual Treadmill", "Woodway", "Curve", "cardio", "Self-paced running", "athletic"],
  ["Recumbent Cycle", "Matrix", "R50", "cardio", "Supported cycling", "low-impact"],
  ["Upright Cycle", "Precor", "UBK 800", "cardio", "Upright cycling", "aerobic"],
  ["Indoor Cycle", "Stages", "SC3", "cardio", "Power-based cycling", "intervals"],
  ["Upper Body Ergometer", "SciFit", "PRO2", "cardio", "Upper-body conditioning", "seated-option"],
  ["Rowing Ergometer", "Concept2", "RowErg", "cardio", "Full-body rowing", "low-impact"],
  ["Ski Ergometer", "Concept2", "SkiErg", "cardio", "Standing or seated poling", "upper-body"],
  [
    "Elliptical Cross-Trainer",
    "Life Fitness",
    "E5",
    "cardio",
    "Low-impact cross-training",
    "low-impact",
  ],
  [
    "Adaptive Motion Trainer",
    "Precor",
    "AMT 885",
    "cardio",
    "Variable-stride cardio",
    "stride-choice",
  ],
  [
    "Lateral Elliptical",
    "Octane",
    "LateralX",
    "cardio",
    "Lateral-plane conditioning",
    "multiplanar",
  ],
  ["Stair Climber", "StairMaster", "8Gx", "cardio", "Continuous stair climbing", "conditioning"],
  [
    "Arm Crank Ergometer",
    "Technogym",
    "Top Excite",
    "cardio",
    "Arm-crank endurance",
    "wheelchair-friendly",
  ],

  [
    "Chest Press",
    "Life Fitness",
    "Insignia",
    "selectorized-strength",
    "Horizontal pressing",
    "upper-body",
  ],
  ["Shoulder Press", "Matrix", "Aura", "selectorized-strength", "Overhead pressing", "upper-body"],
  ["Lat Pulldown", "Precor", "Resolute", "selectorized-strength", "Vertical pulling", "back"],
  [
    "Seated Row",
    "Technogym",
    "Selection 900",
    "selectorized-strength",
    "Supported horizontal pulling",
    "back",
  ],
  [
    "Pec Fly and Rear Delt",
    "Life Fitness",
    "Insignia",
    "selectorized-strength",
    "Chest fly and rear-delt work",
    "dual-purpose",
  ],
  ["Biceps Curl", "Cybex", "Prestige", "selectorized-strength", "Supported elbow flexion", "arms"],
  [
    "Triceps Extension",
    "Cybex",
    "Prestige",
    "selectorized-strength",
    "Supported elbow extension",
    "arms",
  ],
  [
    "Abdominal Crunch",
    "Matrix",
    "Ultra",
    "selectorized-strength",
    "Trunk flexion strength",
    "core",
  ],
  [
    "Back Extension",
    "Precor",
    "Resolute",
    "selectorized-strength",
    "Controlled trunk extension",
    "posterior-chain",
  ],
  [
    "Torso Rotation",
    "Technogym",
    "Selection 900",
    "selectorized-strength",
    "Controlled trunk rotation",
    "core",
  ],
  [
    "Leg Press",
    "Life Fitness",
    "Insignia",
    "selectorized-strength",
    "Supported lower-body pressing",
    "lower-body",
  ],
  [
    "Leg Extension",
    "Matrix",
    "Aura",
    "selectorized-strength",
    "Knee-extension strength",
    "quadriceps",
  ],
  [
    "Seated Leg Curl",
    "Precor",
    "Resolute",
    "selectorized-strength",
    "Knee-flexion strength",
    "hamstrings",
  ],
  [
    "Lying Leg Curl",
    "Life Fitness",
    "Insignia",
    "selectorized-strength",
    "Prone knee-flexion strength",
    "hamstrings",
  ],
  [
    "Hip Abductor",
    "Technogym",
    "Selection 900",
    "selectorized-strength",
    "Hip abduction strength",
    "hip-stability",
  ],
  [
    "Hip Adductor",
    "Technogym",
    "Selection 900",
    "selectorized-strength",
    "Hip adduction strength",
    "hip-strength",
  ],
  [
    "Glute Extension",
    "Matrix",
    "Ultra",
    "selectorized-strength",
    "Supported hip extension",
    "glutes",
  ],
  [
    "Seated Calf Raise",
    "Cybex",
    "Prestige",
    "selectorized-strength",
    "Supported plantar flexion",
    "calves",
  ],

  [
    "Iso-Lateral Chest Press",
    "Hammer Strength",
    "Plate Loaded",
    "plate-loaded-strength",
    "Independent-arm pressing",
    "upper-body",
  ],
  [
    "Iso-Lateral Row",
    "Hammer Strength",
    "Plate Loaded",
    "plate-loaded-strength",
    "Independent-arm rowing",
    "back",
  ],
  [
    "Iso-Lateral Pulldown",
    "Hammer Strength",
    "Plate Loaded",
    "plate-loaded-strength",
    "Independent-arm vertical pulling",
    "back",
  ],
  [
    "Plate-Loaded Shoulder Press",
    "Matrix",
    "Magnum",
    "plate-loaded-strength",
    "Converging overhead press",
    "upper-body",
  ],
  [
    "Hack Squat",
    "Technogym",
    "Pure Strength",
    "plate-loaded-strength",
    "Guided squat pattern",
    "lower-body",
  ],
  [
    "45-Degree Leg Press",
    "Rogers Athletic",
    "Pendulum",
    "plate-loaded-strength",
    "High-capacity leg pressing",
    "lower-body",
  ],
  [
    "Belt Squat",
    "Rogue",
    "Rhino",
    "plate-loaded-strength",
    "Axially reduced squatting",
    "lower-body",
  ],
  [
    "Hip Thrust",
    "Nautilus",
    "Glute Drive",
    "plate-loaded-strength",
    "Supported hip thrusting",
    "glutes",
  ],
  [
    "Standing Calf Raise",
    "Life Fitness",
    "Plate Loaded",
    "plate-loaded-strength",
    "Loaded plantar flexion",
    "calves",
  ],
  [
    "T-Bar Row",
    "Eleiko",
    "Prestera",
    "plate-loaded-strength",
    "Chest-supported rowing",
    "posterior-chain",
  ],

  ["Half Rack", "Eleiko", "Prestera", "free-weights", "Barbell lifting station", "strength"],
  [
    "Power Rack",
    "Rogue",
    "Monster Lite",
    "free-weights",
    "Configurable barbell station",
    "strength",
  ],
  ["Olympic Lifting Platform", "Eleiko", "SVR", "free-weights", "Olympic lifting", "power"],
  [
    "Adjustable Bench",
    "Rogue",
    "Manta Ray",
    "free-weights",
    "Flat and incline support",
    "versatile",
  ],
  [
    "Dumbbell Set 2–50 kg",
    "Eleiko",
    "Evo",
    "free-weights",
    "Incremental dumbbell loading",
    "strength",
  ],
  [
    "Kettlebell Set 4–32 kg",
    "Rogue",
    "Competition",
    "free-weights",
    "Ballistic and grind training",
    "functional",
  ],
  [
    "Fixed Barbell Set",
    "Escape Fitness",
    "Octagon",
    "free-weights",
    "Accessible fixed-load lifting",
    "beginner-friendly",
  ],
  ["Trap Bar", "Eleiko", "Öppen", "free-weights", "Neutral-grip lifting", "posterior-chain"],

  [
    "Dual Adjustable Pulley",
    "Life Fitness",
    "Signature",
    "functional-training",
    "Two-arm cable training",
    "versatile",
  ],
  [
    "Functional Trainer",
    "Technogym",
    "Kinesis One",
    "functional-training",
    "Multi-planar cable training",
    "multiplanar",
  ],
  [
    "Cable Crossover",
    "Matrix",
    "Magnum",
    "functional-training",
    "Wide-span cable exercises",
    "upper-body",
  ],
  [
    "Suspension Training Bay",
    "TRX",
    "S-Frame",
    "functional-training",
    "Bodyweight suspension work",
    "scalable",
  ],
  [
    "Multi-Station Rig",
    "Rogue",
    "Monster Rig",
    "functional-training",
    "Group functional training",
    "group-training",
  ],
  [
    "Sled Track",
    "Escape Fitness",
    "Octagon Track",
    "functional-training",
    "Push and pull conditioning",
    "conditioning",
  ],
  [
    "Battle Rope Station",
    "Torque",
    "X-Rack",
    "functional-training",
    "Rope interval training",
    "conditioning",
  ],
  [
    "Medicine Ball Rebounder",
    "Dynamax",
    "Rebounder",
    "functional-training",
    "Medicine-ball throws",
    "power",
  ],

  [
    "Pilates Reformer",
    "Balanced Body",
    "Allegro 2",
    "pilates-mobility",
    "Spring-resisted Pilates",
    "low-impact",
  ],
  [
    "Clinical Reformer",
    "Merrithew",
    "V2 Max",
    "pilates-mobility",
    "Elevated Pilates access",
    "easy-entry",
  ],
  [
    "Pilates Cadillac",
    "Balanced Body",
    "Trapeze Table",
    "pilates-mobility",
    "Supported mobility and Pilates",
    "supported",
  ],
  [
    "Pilates Chair",
    "Merrithew",
    "Stability Chair",
    "pilates-mobility",
    "Compact spring resistance",
    "balance",
  ],
  [
    "Stretch Trainer",
    "Precor",
    "240i",
    "pilates-mobility",
    "Guided whole-body stretching",
    "mobility",
  ],
  [
    "Mobility Mat Zone",
    "Airex",
    "Corona 200",
    "pilates-mobility",
    "Floor mobility and recovery",
    "floor-work",
  ],

  [
    "Recumbent Stepper",
    "NuStep",
    "T6 Max",
    "rehabilitation",
    "Total-body recumbent stepping",
    "accessible-cardio",
  ],
  [
    "Body-Weight Support Treadmill",
    "AlterG",
    "Anti-Gravity",
    "rehabilitation",
    "Reduced-load walking and running",
    "gait-training",
  ],
  [
    "Cable Column with Removable Seat",
    "SciFit",
    "Proformance",
    "rehabilitation",
    "Seated or standing cable exercise",
    "wheelchair-friendly",
  ],
  [
    "Parallel Bars",
    "Hausmann",
    "Powermatic",
    "rehabilitation",
    "Supported gait and balance practice",
    "stable-support",
  ],
] satisfies EquipmentSeed[];

const categoryDefaults: Record<
  EquipmentCategory,
  {
    dimensions: { length: number; width: number; height: number };
    clearance: number;
    power: Equipment["power"];
    capabilities: string[];
    accessibility: string[];
    zone: string;
  }
> = {
  cardio: {
    dimensions: { length: 210, width: 92, height: 160 },
    clearance: 60,
    power: "120v",
    capabilities: ["Cardiorespiratory conditioning", "Adjustable intensity"],
    accessibility: ["Emergency stop", "Multiple intensity levels"],
    zone: "Cardio",
  },
  "selectorized-strength": {
    dimensions: { length: 150, width: 120, height: 165 },
    clearance: 45,
    power: "none",
    capabilities: ["Guided resistance", "Incremental load selection"],
    accessibility: ["Low starting resistance", "High-contrast adjustment markers"],
    zone: "Guided Strength",
  },
  "plate-loaded-strength": {
    dimensions: { length: 185, width: 145, height: 155 },
    clearance: 60,
    power: "none",
    capabilities: ["Plate-loaded resistance", "Progressive strength training"],
    accessibility: ["Stable entry handles"],
    zone: "Plate Loaded",
  },
  "free-weights": {
    dimensions: { length: 245, width: 180, height: 240 },
    clearance: 90,
    power: "none",
    capabilities: ["Free-weight training", "Scalable external load"],
    accessibility: ["Open approach area"],
    zone: "Free Weights",
  },
  "functional-training": {
    dimensions: { length: 250, width: 180, height: 235 },
    clearance: 90,
    power: "none",
    capabilities: ["Multi-planar training", "Adjustable movement patterns"],
    accessibility: ["Multiple attachment heights", "Open training area"],
    zone: "Functional",
  },
  "pilates-mobility": {
    dimensions: { length: 240, width: 80, height: 95 },
    clearance: 60,
    power: "none",
    capabilities: ["Mobility", "Controlled low-impact resistance"],
    accessibility: ["Instructor-assisted setup available"],
    zone: "Mind & Body",
  },
  rehabilitation: {
    dimensions: { length: 200, width: 100, height: 145 },
    clearance: 90,
    power: "120v",
    capabilities: ["Supported exercise", "Fine-grained progression"],
    accessibility: ["Wide approach path", "Support handles", "Staff setup available"],
    zone: "Adaptive Training",
  },
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const catalogInput = equipmentSeeds.map(
  ([name, manufacturer, model, category, capability, suitability], index) => {
    const defaults = categoryDefaults[category];
    const number = String(index + 1).padStart(3, "0");
    return {
      id: `eq_${number}`,
      slug: `${slugify(name)}-${number}`,
      name,
      manufacturer,
      model,
      category,
      summary: `${name} supports ${capability.toLowerCase()} in the Adaptive Gym synthetic demonstration catalog. Specifications are illustrative and should be verified before procurement.`,
      dimensionsCm: defaults.dimensions,
      requiredClearanceCm: defaults.clearance,
      maxUserWeightKg: category === "free-weights" ? undefined : 180,
      power: defaults.power,
      stations: name.includes("Multi-Station") ? 6 : 1,
      capabilities: [...defaults.capabilities, capability],
      accessibility: defaults.accessibility,
      suitabilityTags: [suitability, category, "demo-catalog"],
      locationZone: defaults.zone,
      available: index !== 11 && index !== 37,
      syntheticCatalogEntry: true as const,
    };
  },
);

export const equipmentCatalog = EquipmentCatalogSchema.parse(catalogInput);

export const equipmentCatalogById = new Map(
  equipmentCatalog.map((equipment) => [equipment.id, equipment] as const),
);

export const equipmentCategories = [
  ...new Set(equipmentCatalog.map((equipment) => equipment.category)),
];
