"use client";

import { useState } from "react";
import { Icon } from "@/components/icon";
import { PageHeading, PortalShell } from "@/components/shell";
import { formatPassportDate } from "@/lib/date-format";
import type { SavedRoutineDetail } from "@/lib/saved-routines";

const EXPERT_REVIEW_WARNING =
  "AI-generated personalized draft. A physician or qualified physical therapist should review and approve this routine before it is performed.";

export function SavedRoutineView({ routine }: { routine: SavedRoutineDetail }) {
  const [completedStations, setCompletedStations] = useState<Set<number>>(() => new Set());
  const agentGenerated =
    routine.generationMode === "agent_generated" || routine.templateId === "webmcp_agent_generated";

  return (
    <PortalShell view="dashboard" title="Saved routine">
      <PageHeading
        eyebrow={agentGenerated ? "Agent-generated via WebMCP" : "Saved to your Passport"}
        title={routine.title}
        description={`${routine.durationMinutes} minutes · Saved ${formatPassportDate(routine.savedAt)}`}
        selector={false}
      />
      <div className="dashboard-grid">
        <div className="stack">
          {routine.requiresExpertReview ? (
            <section className="card" style={{ background: "#fff4df" }}>
              <div className="progressive-note" style={{ margin: 0 }}>
                <Icon name="info" width="17" />
                <span>
                  <strong>{EXPERT_REVIEW_WARNING}</strong>
                  {routine.expertReviewReason ? ` ${routine.expertReviewReason}` : ""}
                </span>
              </div>
            </section>
          ) : null}

          {routine.warmup.length ? <RoutineSteps title="Warm-up" values={routine.warmup} /> : null}

          <section className="card">
            <div className="card-header">
              <div>
                <h2>Exercise checklist</h2>
                <p className="card-subtitle">
                  {agentGenerated
                    ? "Generated by the user-selected agent and validated against verified Gym equipment"
                    : "Public staff walkthrough grounded in verified equipment"}
                </p>
              </div>
              <span className="pill">
                {completedStations.size}/{routine.exercises.length} complete
              </span>
            </div>
            <div className="scope-list">
              {routine.exercises.map((exercise, index) => (
                <article className="scope" key={`${exercise.equipmentId}-${index}`}>
                  <div className="scope-main" style={{ alignItems: "flex-start" }}>
                    <div className="scope-icon">
                      <input
                        aria-label={`Mark exercise ${index + 1}, ${exercise.name}, complete`}
                        checked={completedStations.has(index)}
                        type="checkbox"
                        onChange={(event) => {
                          setCompletedStations((current) => {
                            const next = new Set(current);
                            if (event.target.checked) next.add(index);
                            else next.delete(index);
                            return next;
                          });
                        }}
                      />
                    </div>
                    <div>
                      <strong>{exercise.name}</strong>
                      <small>
                        {exercise.durationMinutes
                          ? `${exercise.durationMinutes} minutes`
                          : `${exercise.sets ?? "—"} sets · ${exercise.reps ?? "guided reps"}`}{" "}
                        · {exercise.intensity}
                      </small>
                      <div className="scope-list" style={{ marginTop: 8 }}>
                        {exercise.instructions.map((instruction) => (
                          <small key={instruction}>{instruction}</small>
                        ))}
                      </div>
                      <div className="progressive-note" style={{ marginTop: 10 }}>
                        <Icon name="spark" width="15" />
                        <span>{exercise.adaptationReason}</span>
                      </div>
                    </div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <strong>{exercise.manufacturer}</strong>
                    <small style={{ display: "block" }}>{exercise.model}</small>
                    {exercise.sourceUrl ? (
                      <a
                        className="text-link"
                        href={exercise.sourceUrl}
                        target="_blank"
                        rel="noreferrer"
                      >
                        Manufacturer source
                      </a>
                    ) : null}
                  </div>
                </article>
              ))}
            </div>
          </section>

          {routine.cooldown.length ? (
            <RoutineSteps title="Cooldown" values={routine.cooldown} />
          ) : null}

          <section className="card">
            <div className="card-header">
              <div>
                <h2>Safety notes</h2>
                <p className="card-subtitle">Keep these visible throughout the routine</p>
              </div>
            </div>
            <div className="scope-list">
              {routine.safetyNotes.map((note) => (
                <div className="scope" key={note}>
                  <div className="scope-main">
                    <div className="scope-icon">
                      <Icon name="shield" width="15" />
                    </div>
                    <strong>{note}</strong>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        <aside className="stack">
          <section className="card">
            <div className="card-header">
              <div>
                <h2>Provenance</h2>
                <p className="card-subtitle">
                  Authoritative context and catalog metadata saved with this snapshot
                </p>
              </div>
            </div>
            <div className="data-list">
              <div className="data-row">
                <span>Your stated goal</span>
                <strong>{routine.goal}</strong>
              </div>
              <div className="data-row">
                <span>Generation</span>
                <strong>
                  {agentGenerated ? "Agent-generated via WebMCP" : "Public staff walkthrough"}
                </strong>
              </div>
              {agentGenerated ? null : (
                <div className="data-row">
                  <span>Walkthrough</span>
                  <strong>{routine.templateId}</strong>
                </div>
              )}
              <div className="data-row">
                <span>Provenance version</span>
                <strong>{routine.templateVersion}</strong>
              </div>
              <div className="data-row">
                <span>Catalog version</span>
                <strong>{routine.catalogVersion}</strong>
              </div>
              <div className="data-row">
                <span>Created via</span>
                <strong>{routine.createdVia === "webmcp" ? "WebMCP" : "Gym site"}</strong>
              </div>
            </div>
          </section>

          <section className="card">
            <div className="card-header">
              <div>
                <h2>Validation trace</h2>
                <p className="card-subtitle">
                  Why Adaptive Gym accepted and saved this exact routine
                </p>
              </div>
            </div>
            <div className="scope-list">
              {routine.decisionTrace.map((reason) => (
                <div className="scope" key={reason}>
                  <div className="scope-main">
                    <div className="scope-icon">
                      <Icon name="check" width="14" />
                    </div>
                    <small>{reason}</small>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="card" style={{ background: "#fff4df" }}>
            <div className="progressive-note" style={{ margin: 0 }}>
              <Icon name="info" width="17" />
              <span>
                Synthetic demonstration only. This routine is non-clinical and is not medical
                advice, diagnosis, treatment, clearance, or emergency guidance.
              </span>
            </div>
          </section>
        </aside>
      </div>
    </PortalShell>
  );
}

function RoutineSteps({ title, values }: { title: string; values: readonly string[] }) {
  return (
    <section className="card">
      <div className="card-header">
        <div>
          <h2>{title}</h2>
        </div>
      </div>
      <div className="scope-list">
        {values.map((value) => (
          <div className="scope" key={value}>
            <div className="scope-main">
              <div className="scope-icon">
                <Icon name="check" width="14" />
              </div>
              <strong>{value}</strong>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
