import type { Equipment, GymContextProjection, RoutineProOffer } from "@adaptive-world/contracts";
import type {
  CreatePersonalizedRoutineInput,
  MutationConfirmationRequest,
  RecordSessionFeedbackInput,
  WebMCPMutationPreparation,
} from "@adaptive-world/webmcp";
import { pendingPaymentMode, type PendingRoutineProOrder } from "./routine-pro-client-state";
import { PROFESSIONAL_REVIEW_WARNING } from "./session-planner";

export type PreparedRoutineProConfirmation = Readonly<{
  effectiveInput: CreatePersonalizedRoutineInput;
  preparation: WebMCPMutationPreparation;
}>;

export function prepareRoutineProConfirmation({
  offer,
  requestedInput,
  pending,
  projection,
  selectedEquipment,
}: {
  offer: RoutineProOffer;
  requestedInput: CreatePersonalizedRoutineInput;
  pending: PendingRoutineProOrder | null;
  projection: GymContextProjection;
  selectedEquipment: readonly Equipment[];
}): PreparedRoutineProConfirmation {
  const effectiveInput: CreatePersonalizedRoutineInput = {
    ...requestedInput,
    goal: requestedInput.goal.trim(),
    ...(pending ? { paymentMode: pendingPaymentMode(pending) } : {}),
  };
  if (pending?.initialGoal && pending.initialGoal !== effectiveInput.goal) {
    throw new Error("The pending order was confirmed for a different goal.");
  }
  const payer = offer.entitled
    ? "Existing Passport entitlement"
    : (pending?.payerLabel ??
      (effectiveInput.paymentMode === "agent_wallet"
        ? "Adaptive World demo agent"
        : "Human test checkout"));
  const routine = effectiveInput.routine;
  const equipmentById = new Map(selectedEquipment.map((item) => [item.id, item]));
  const routineFields = routine.exercises.map((exercise, index) => {
    const item = equipmentById.get(exercise.equipmentId);
    return {
      label: `Exercise ${index + 1}`,
      value: `${item?.name ?? exercise.equipmentId} (${exercise.equipmentId}) · ${exercise.durationMinutes} min · ${exercise.intensity} · ${exercise.instructions.join(" / ")} · Why: ${exercise.adaptationReason}`,
    };
  });

  return {
    effectiveInput,
    preparation: {
      confirmation: {
        title: pending
          ? "Recover the existing Routine Pro payment?"
          : offer.entitled
            ? "Save this exact agent-generated routine?"
            : "Approve this exact routine and sandbox payment?",
        description: pending
          ? "This resumes only the existing payment state for the exact agent-generated routine already staged by Adaptive Gym. It must not create a second payment."
          : "This exact routine was generated by the user-selected agent. Adaptive Gym will validate it against the approved Passport projection and verified Gym inventory, hydrate authoritative equipment facts, process the sandbox payment if needed, and save the validated result to Passport.",
        fields: [
          { label: "Product", value: offer.displayName },
          { label: "Proposed routine", value: `${routine.title} · ${routine.durationMinutes} minutes` },
          { label: "Your goal", value: effectiveInput.goal },
          {
            label: "Approved Passport context",
            value: `${projection.projectionId} · goals: ${projection.goals.slice(0, 3).join("; ")} · ${projection.stopSignals.length} stop signal(s) · ${projection.movementConsiderations.length} movement consideration(s)`,
          },
          {
            label: "Verified Gym equipment",
            value: selectedEquipment.length
              ? selectedEquipment.map((item) => `${item.name} (${item.id})`).join("; ")
              : "None",
          },
          ...routineFields,
          ...(routine.warmup?.length
            ? [{ label: "Warm-up", value: routine.warmup.join(" / ") }]
            : []),
          ...(routine.cooldown?.length
            ? [{ label: "Cooldown", value: routine.cooldown.join(" / ") }]
            : []),
          {
            label: "Safety notes",
            value: routine.safetyNotes.length ? routine.safetyNotes.join(" / ") : "None submitted",
          },
          {
            label: "Professional review",
            value: routine.requiresExpertReview
              ? `${PROFESSIONAL_REVIEW_WARNING} ${routine.expertReviewReason ?? ""}`.trim()
              : "Not requested by the submitted draft; Adaptive Gym may still require it from the active Passport context.",
          },
          { label: "Payer", value: payer },
          {
            label: "Amount",
            value: offer.entitled ? "Already unlocked" : "$4.99 test USD",
          },
          { label: "Payment network", value: "Sandbox/testnet — no real funds" },
          { label: "Save destination", value: "Passport saved routines" },
          { label: "Data access", value: "Unchanged; only the active consented Gym projection" },
        ],
        riskClass: offer.entitled ? "account-write" : "payment",
        confirmLabel: pending
          ? "Recover existing payment"
          : offer.entitled
            ? "Save exact routine"
            : effectiveInput.paymentMode === "agent_wallet"
              ? "Approve exact routine + agent payment"
              : "Approve exact routine + test checkout",
        cancelLabel: "Cancel",
      },
      quoteDigest: offer.quoteDigest,
    },
  };
}

export function webMcpMutationBusyLabel(request: MutationConfirmationRequest): string {
  if (request.toolName !== "create_personalized_routine") {
    return "Saving confirmed changes…";
  }
  const payer = request.fields.find((field) => field.label === "Payer")?.value;
  if (payer === "Adaptive World demo agent") {
    return "Paying for and saving the confirmed agent-generated routine…";
  }
  if (payer === "Human test checkout") {
    return "Opening secure Stripe test checkout for the confirmed routine…";
  }
  return "Saving the confirmed agent-generated routine to Passport…";
}

export function prepareFeedbackConfirmation(
  input: RecordSessionFeedbackInput,
  completedExerciseIds: readonly string[],
): WebMCPMutationPreparation {
  return {
    confirmation: {
      title: "Record session feedback",
      description: "Review the exact feedback that will be saved to this Gym session.",
      fields: [
        { label: "Public routine reference", value: input.sessionId },
        { label: "Perceived exertion", value: String(input.perceivedExertion ?? 5) },
        { label: "Pain", value: String(input.pain ?? 0) },
        {
          label: "Completed station IDs",
          value: completedExerciseIds.length ? completedExerciseIds.join(", ") : "None",
        },
        { label: "Notes", value: input.notes ?? "None" },
      ],
      riskClass: "account-write",
      confirmLabel: "Save exact feedback",
      cancelLabel: "Cancel",
    },
  };
}
