"use client";

import type { GymContextProjection } from "@adaptive-world/contracts";
import {
  Check,
  ChevronRight,
  Clock3,
  Fingerprint,
  KeyRound,
  LockKeyhole,
  ShieldCheck,
  UserRound,
} from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Props = { profiles: GymContextProjection[] };

export function ContextPassport({ profiles }: Props) {
  const router = useRouter();
  const [selectedId, setSelectedId] = useState(profiles[0]?.projectionId ?? "");
  const [activeId, setActiveId] = useState<string | null>(null);
  const [grantCode, setGrantCode] = useState("");
  const [grantMessage, setGrantMessage] = useState<string | null>(null);

  useEffect(() => {
    setActiveId(window.localStorage.getItem("adaptive-gym-context"));
  }, []);
  const selected = profiles.find((profile) => profile.projectionId === selectedId);

  function connect(profileId = selectedId) {
    window.localStorage.setItem("adaptive-gym-context", profileId);
    setActiveId(profileId);
    router.push("/session");
  }

  async function redeemGrant() {
    setGrantMessage(null);
    const response = await fetch("/api/context/redeem", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ code: grantCode }),
    });
    const data = (await response.json()) as { projection?: GymContextProjection; error?: string };
    if (!response.ok || !data.projection) {
      setGrantMessage(data.error ?? "That code could not be redeemed.");
      return;
    }
    setSelectedId(data.projection.projectionId);
    window.localStorage.setItem("adaptive-gym-context", data.projection.projectionId);
    setActiveId(data.projection.projectionId);
    setGrantMessage("Context grant redeemed. The one-time code is now closed.");
  }

  return (
    <div className="passport-layout">
      <section className="passport-picker card">
        <div className="panel-heading">
          <span className="panel-heading__icon">
            <UserRound size={19} />
          </span>
          <div>
            <p>Demo participants</p>
            <h2>Choose a minimum projection</h2>
          </div>
        </div>
        <div className="profile-list">
          {profiles.map((profile) => (
            <button
              type="button"
              key={profile.projectionId}
              className={
                selectedId === profile.projectionId
                  ? "profile-option is-selected"
                  : "profile-option"
              }
              onClick={() => setSelectedId(profile.projectionId)}
            >
              <span className="profile-avatar">
                {profile.subjectAlias
                  .split(" ")
                  .map((word) => word[0])
                  .slice(0, 2)
                  .join("")}
              </span>
              <span>
                <strong>{profile.subjectAlias}</strong>
                <small>
                  {profile.ageBand} · {profile.experienceLevel}
                </small>
              </span>
              {activeId === profile.projectionId ? (
                <span className="tag tag--green">
                  <Check size={12} /> Active
                </span>
              ) : (
                <ChevronRight size={17} />
              )}
            </button>
          ))}
        </div>
        <div className="grant-box">
          <div>
            <KeyRound size={18} />
            <strong>Have a context grant?</strong>
          </div>
          <p>
            Redeem a one-time code generated by the Passport app. For this demo, try{" "}
            <code>demo-mateo</code>.
          </p>
          <div className="grant-input">
            <input
              value={grantCode}
              onChange={(event) => setGrantCode(event.target.value)}
              placeholder="Enter grant code"
            />
            <button type="button" onClick={() => void redeemGrant()} disabled={!grantCode.trim()}>
              Redeem
            </button>
          </div>
          {grantMessage && (
            <p className="grant-message" role="status">
              {grantMessage}
            </p>
          )}
        </div>
      </section>

      <section className="projection-card" aria-live="polite">
        {selected ? (
          <>
            <div className="projection-card__top">
              <div>
                <p className="eyebrow">Gym projection preview</p>
                <h2>{selected.subjectAlias}</h2>
                <p>This is the full set of context Adaptive Gym receives.</p>
              </div>
              <Fingerprint size={38} />
            </div>
            <div className="projection-summary">
              <div>
                <span>Age range</span>
                <strong>{selected.ageBand}</strong>
              </div>
              <div>
                <span>Experience</span>
                <strong>{selected.experienceLevel}</strong>
              </div>
              <div>
                <span>Session</span>
                <strong>{selected.preferredSessionMinutes} min</strong>
              </div>
            </div>
            <ContextSection title="Goals" values={selected.goals} />
            <ContextSection
              title="Movement considerations"
              values={selected.movementConsiderations}
              emphasis
            />
            {selected.accessibilityNeeds.length > 0 && (
              <ContextSection title="Access needs" values={selected.accessibilityNeeds} />
            )}
            <ContextSection title="Stop signals" values={selected.stopSignals} danger />
            <div className="privacy-boundary">
              <LockKeyhole size={18} />
              <p>
                <strong>Not shared:</strong> name, birthday, contact details, diagnoses,
                medications, laboratories, documents and clinician identity.
              </p>
            </div>
            <div className="projection-expiry">
              <Clock3 size={14} /> Valid until{" "}
              {new Date(selected.expiresAt).toLocaleDateString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
              })}
            </div>
            <button
              className="button button--lime button--block"
              type="button"
              onClick={() => connect()}
            >
              <ShieldCheck size={18} /> Use this context in Adaptive Gym
            </button>
          </>
        ) : (
          <p>No projection selected.</p>
        )}
      </section>
    </div>
  );
}

function ContextSection({
  title,
  values,
  emphasis,
  danger,
}: {
  title: string;
  values: string[];
  emphasis?: boolean;
  danger?: boolean;
}) {
  return (
    <div className="context-section">
      <h3>{title}</h3>
      <div className="tag-cloud">
        {values.map((value) => (
          <span
            className={danger ? "tag tag--orange" : emphasis ? "tag tag--green" : "tag"}
            key={value}
          >
            {value}
          </span>
        ))}
      </div>
    </div>
  );
}
